apiVersion: v1
imagePullSecrets:
- name: deployer-dockercfg-d4fgf
kind: ServiceAccount
metadata:
  name: deployer
  namespace: guestbook
secrets:
- name: deployer-dockercfg-d4fgf
- name: deployer-token-v7zdz
